version: '1'

services:
  app:
    build: .
    volumes:
      - .:/app
    restart: no
    environment:
      - DEBUG
      - DJANGO_SECRET_KEY
      - ALLOWED_HOSTS
      - DB_ENGINE
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - DEPLOY_ENV
    ports:
      - ${SERVICE_PORT:-8002}:8000
    profiles:
      - dev
    depends_on:
      - my-postgres
    networks:
      - patient

  my-postgres:
    image: postgres
    restart: no
    ports:
      - 5433:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    networks:
      - patient

volumes:
  data:

networks:
  patient:
    driver: bridge
