# Generated by Django 5.0.3 on 2024-04-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('number', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
    ]
